### ISSUE TITLE
HardFault trying to use saved Sub-Ghz 

### ISSUE THREAD

**Issue by SharpEdgeMarshall** [flipperdevices/flipperzero-firmware#1457]
### Describe the bug.

Every time I try to "Emulate" a Sub-Ghz remote that I saved before, Flipper Zero power off and I have to use the reset sequence to restart it (a message will appear saying that FlipperZero was restarted cause of a HardFault)

### Reproduction

1. Go to Sub-Ghz
2. Read remote (CAME TWEE) on 433.92 AM270
3. Save it or press send 
4. Flipper zero will shutdown instantly

### Target

Remote model: ENTREMATIC ZEN4

### Logs

```Text
How do i find logs?
```

**Comment by Skorpionm** [comment]
https://github.com/flipperdevices/flipperzero-firmware/pull/1446
if you really use the CAME TWEE remote control, there will be no more errors.  if not this protocol, then it will not be identified, the error was due to an incorrect definition of the protocol

**Comment by skotopes** [comment]
fixed in 0.63.0-rc

**Comment by SharpEdgeMarshall** [comment]
@skotopes is detected as CAME TWEE but is a ENTREMATIC ZEN4 how can I know if it is normal?

**Comment by skotopes** [comment]
@SharpEdgeMarshall if emulation works then it's normal )

**Comment by SharpEdgeMarshall** [comment]
@skotopes I tried the `0.63.1` and the issue is still there :/

**Comment by Skorpionm** [comment]
then please write me a raw file with this remote control and send
