### ISSUE TITLE
Detect SL (sweden transport card) NFC

### ISSUE THREAD

**Issue by xSean145** [flipperdevices/flipperzero-firmware#2465]
### Describe the enhancement you're suggesting.

Flipper Zero does not detect or read this card. Add support to detect and read this card.
Proxmark pulled this info from the card. (UID censored)

[usb] pm3 --> hf search
 🕕  Searching for ISO14443-A tag...          
[+]  UID: XX XX XX XX XX XX XX 
[+] ATQA: 00 44
[+]  SAK: 60 [1]
[+] MANUFACTURER: Infineon Technologies AG Germany
[=] -------------------------- ATS --------------------------
[+] ATS: 0B 78 80 74 03 80 54 05 30 3E 0F [ CF 00 ]
[=]      0B...............  TL    length is 11 bytes
[=]         78............  T0    TA1 is present, TB1 is present, TC1 is present, FSCI is 8 (FSC = 256)
[=]            80.........  TA1   different divisors are NOT supported, DR: [], DS: []
[=]               74......  TB1   SFGI = 4 (SFGT = 65536/fc), FWI = 7 (FWT = 524288/fc)
[=]                  03...  TC1   NAD is supported, CID is supported

[=] -------------------- Historical bytes --------------------
[+]   805405303E0F  (compact TLV data object)
[=]     54  05303E0F   Card issuer data

[?] Hint: try `hf mfu info`

[+] Valid ISO 14443-A tag found

[=] Short AID search:
[?] Hint: try emv commands

### Anything else?

It is recognized as a iso14443-4a.

**Comment by Astrrra** [comment]
Does it not react to the card at all? Or does it at least show the UID?

**Comment by xSean145** [comment]
It does not react at all to the card. I was told in Discord it might be something with the unusual SAK.
Can send you all the files pulled from the card there.

**Comment by skotopes** [comment]
Yep, we do need more details. And most likely physical card.

**Comment by xSean145** [comment]
I can send the physical card to anywhere in the world. Can I contact someone on Discord?

**Comment by skotopes** [comment]
@xSean145 you can ping me skotopes#4130

**Comment by bidhata** [comment]
any updates on this ?

**Comment by skotopes** [comment]
@bidhata not really, we still don't have card for analysis.

**Comment by idoo** [comment]
Has the issue been resolved with the latest release? 
https://github.com/flipperdevices/flipperzero-firmware/pull/3017

**Comment by xSean145** [comment]
Its not.
I did send the card out to one of the devs but it was returned to me as it was unclaimed at the postal office. I will see if I can get it sent out again.

**Comment by mxcdoam** [comment]
I have 4 units of SL cards (older MFC 1K and newer MF PLUS 4K)and I can read both on 0.97.1 FW (keys are available in system dict). No parser though.

**Comment by skotopes** [comment]
@xSean145 do you still have the card? Does latest firmware works for you?

**Comment by xSean145** [comment]
Still have the card. Never got a second adress to send it to. The first one i sent got returned to me because it was unclaimed. Will try new firmware once im back from traveling.

**Comment by skotopes** [comment]
@xSean145 ok. Since we moved NFC team to our UK office you can send it here directly. Ping me when if you'll need address.
